version: "3.5"

services:
  valguero:
    image: r15ch13/arkcluster:latest
    restart: unless-stopped
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "0 */3 * * *"
      CRON_AUTO_BACKUP: "0 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: ${TZ}
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Valguero_P"
      SESSION_NAME: "${SERVER_NAME} - Valguero"
      MAX_PLAYERS: 12
      RCON_ENABLE: ${RCON_ENABLE}
      RCON_PORT: 32330
      GAME_PORT: 7777
      QUERY_PORT: 27015
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPECTATOR_PASSWORD: "iLikeToWatch"
      MODS: ${MODS}
      CLUSTER_ID: ${CLUSTER_ID}
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - ${SERVER_DATAFILES}/valguero:/ark
      - ${SERVER_DATAFILES}/cluster:/cluster
    ports:
      - "32330:32330/tcp"
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"
    networks:
      - ark

  genesis2:
    image: r15ch13/arkcluster:latest
    restart: unless-stopped
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "15 */3 * * *"
      CRON_AUTO_BACKUP: "15 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: ${TZ}
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Gen2"
      SESSION_NAME: "${SERVER_NAME} - Genesis 2"
      MAX_PLAYERS: 15
      RCON_ENABLE: ${RCON_ENABLE}
      RCON_PORT: 32331
      GAME_PORT: 7779
      QUERY_PORT: 27017
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPECTATOR_PASSWORD: "iLikeToWatch"
      MODS: ${MODS}
      CLUSTER_ID: ${CLUSTER_ID}
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - ${SERVER_DATAFILES}/gen2:/ark
      - ${SERVER_DATAFILES}/cluster:/cluster
    ports:
      - "32331:32331/tcp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "27017:27017/udp"
    networks:
      - ark

  aberration:
    image: r15ch13/arkcluster:latest
    restart: unless-stopped
    deploy:
      mode: global
    environment:
      CRON_AUTO_UPDATE: "30 */3 * * *"
      CRON_AUTO_BACKUP: "30 */1 * * *"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: ${TZ}
      MAX_BACKUP_SIZE: 500
      SERVERMAP: "Aberration_P"
      SESSION_NAME: "${SERVER_NAME} - Aberration"
      MAX_PLAYERS: 15
      RCON_ENABLE: ${RCON_ENABLE}
      RCON_PORT: 32331
      GAME_PORT: 7781
      QUERY_PORT: 27019
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPECTATOR_PASSWORD: "iLikeToWatch"
      MODS: ${MODS}
      CLUSTER_ID: ${CLUSTER_ID}
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - ${SERVER_DATAFILES}/aberration:/ark
      - ${SERVER_DATAFILES}/cluster:/cluster
    ports:
      - "32332:32332/tcp"
      - "7781:7781/udp"
      - "7782:7782/udp"
      - "27019:27019/udp"
    networks:
      - ark
 
networks:
  ark: {}