version: "3"

services:
  valcord:
    build:
      context: valcord
    environment:
      BOT_TOKEN: ${DISCORD_TOKEN}
      SERVER_ADDRESS: valheim
      SERVER_PORT: ${SERVER_PORT}
      SERVER_NAME: ${DISCORD_BOT_NAME}
      CHANNEL_NAME: ${CHANNEL_NAME}
    container_name: valcord
    networks:
      - valheim
    restart: unless-stopped
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - config:/config
      - serverfiles:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_PASS: ${SERVER_PASS}
      SERVER_PUBLIC: ${SERVER_PUBLIC}
      ADMINLIST_IDS: ${ADMINLIST_IDS}
      TZ: ${TZ}
      WORLD_NAME: ${WORLD_NAME}
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  config:
  serverfiles:
  
networks:
  valheim: {}