version: "3.5"

services:
  icarus:
    image: mastermnb/icarus-dedicated-server:latest    
    container_name: icarus
    init: true
    restart: unless-stopped
    networks:
      - icarus
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      - "${SERVER_QUERYPORT}:${SERVER_QUERYPORT}/udp"
    environment:
      - ASYNC_TIMEOUT=60
      - BRANCH=public
      - AUTOUPDATE=1
      - SERVERNAME=${SERVER_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - QUERY_PORT=${SERVER_QUERYPORT}
      - JOIN_PASSWORD=${PASSWORD}
      - MAX_PLAYERS=8
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ${SERVER_DATAFILES}:/home/container/icarus/drive_c/icarus
      - game:/home/container/game/icarus
      
networks:
  icarus: {}
  
volumes:
  game: {}